### ISSUE TITLE
installation requirement of sklearn

### ISSUE THREAD

**Issue by z5ouyang** [QihuangZhang/CeLEry#3] opened 2024-01-04 22:43 UTC
Hi,
was trying to install the "CeLEry" with following error:
![image](https://github.com/QihuangZhang/CeLEry/assets/30639029/7bbb3c48-e870-490b-88c1-ffeabcda749c)

**Comment by QihuangZhang** [comment] 2024-01-05 04:45
It seems like the problem is with the installation of sklearn. Can you try running  `pip install scikit-learn` before installing CeLEry?

**Comment by z5ouyang** [comment] 2024-01-05 05:55
Thanks for the reply! I did have scikit-learn installed. But since "sklearn" in "pyproject.toml", CeLEry cannot be installed because 'sklearn' is not available even scikit-learn is installed.
If you just change "sklearn" to "scikit-learn" in "pyproject.toml" It should work. I did clone, after update the "pyproject.toml", pip build/install were successful.

**Comment by QihuangZhang** [comment] 2024-01-05 14:51
Thank you for spotting this!! I have made the update.

**Comment by QihuangZhang** [comment] 2024-01-19 21:10
Issue closed as it is completed

**Closed as completed** 2024-01-19 21:10 UTC
